name: Test Workflow CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
            path: ~/.m2/repository
            key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            restore-keys: |
                  ${{ runner.os }}-maven-

#      tạo 2 folder chrome-linux64 và firefox
      - name: cd to resources
        working-directory: ./src/test/resources
        run: |
          mkdir -p chrome-linux64
          ls

      - name: Download and extract Firefox
        working-directory: ./src/test/resources
        run: |
         touch created
         wget -O firefox.tar.xz "https://download.mozilla.org/?product=firefox-latest&os=linux64&lang=en-US"
         tar -xJf firefox.tar.xz
         chmod +x firefox/firefox
         ls -l firefox/firefox
         ls -al
    


      - name: Download gecko
        working-directory: ./src/test/resources
        run: |
          wget -O geckodriver.tar.gz "https://github.com/mozilla/geckodriver/releases/download/v0.36.0/geckodriver-v0.36.0-linux64.tar.gz"
          tar -xzf geckodriver.tar.gz
          chmod +x geckodriver
          ls -l geckodriver
          ls

      - name: Runtest Firefox
        run: |
          mvn test -P firefox
